# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#

version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:16.0.1-jdk-buster

    working_directory: ~/repo

    steps:
      # git pull
      - checkout

      # setup testing env
      # the following commented lines are not allowed in the free version of circleci
      #       - setup_remote_docker:
      #           docker_layer_caching: true
      - run:
          name: Login to DockerHub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # package into a tar
      - run: ./gradlew clean disTar

      # create Distributable
      - run: ./gradlew createDistributable

      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: false

      # build and push docker image to docker hub
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build --tag=fruakumawah/birthcertificate:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push fruakumawah/birthcertificate:$TAG
